### ISSUE TITLE
i want to compile your source in window 10 home 32bit environment

### ISSUE THREAD

**Issue by Zansword** [wuziq/ggpofba#2]
I tried to compile this with your option what you said, but there is only this error message.
could you help me?

C:\Users\zan\Desktop\ggpofba>make vc
make[1]: *** [init] Error -99
make: *** [vc] Error 2

**Comment by wuziq** [comment]
Sorry, I've only tried the platforms indicated in the readme.  I'm archiving this project as I don't have any plans to work on it.
