### ISSUE TITLE
64 bits version

### ISSUE THREAD

**Issue by khurtado** [wuziq/ggpofba#3]
Is it possible to compile this in 64 bits?

Projects like fightcade depend on `ggpofba-ng.exe`, which is 32 bits and no longer supported in Mac Os X Catalina, so I was wondering if it is possible to compile a `ggpofba64-ng.exe` and if this has been provided already or not

https://github.com/poliva/pyqtggpo

**Comment by wuziq** [comment]
Sorry, I've only tried the platforms indicated in the readme.  I have no idea whether FBA has any architecture-specific dependencies.

I'm archiving this project as I don't have any plans to work on it.
